spring:
  application:
    name: Spring-shop
  profiles:
    active: local
  jta:
    enabled: false
  jpa:
    open-in-view: false
    driver-class-name: org.postgresql.Driver
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: create.sql

  cache: 
    jcache:
      config: classpath:cache/ehcache.xml
logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    fr.training.samples.spring.shop: INFO