spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
#force data.sql script execution
    initialization-mode: always

logging:
  level:
    root: info
    org.springframework.batch: info
    com.zaxxer.hikari.HikariDataSource: warn
    
# Logging Configurations
application: 
  orgEntity: BDDF
  version: '@project.version@'
  timezone: ${user.timezone}
  apCode: AP2020
  type: service_logs    